import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy - WishDrop",
  description: "WishDrop Privacy Policy — how we collect, use, and protect your data.",
};

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-wd-cream">
      <div className="max-w-3xl mx-auto px-4 py-16">
        <Link href="/" className="text-sm text-wd-gold hover:underline mb-8 inline-block">&larr; Back to Home</Link>

        <h1 className="text-4xl font-bold text-wd-heading font-display mb-2">Privacy Policy</h1>
        <p className="text-sm text-wd-charcoal/50 mb-10">Last updated: March 28, 2026</p>

        <div className="prose-sm space-y-8 text-wd-charcoal/80 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-wd-heading mb-3">1. Overview</h2>
            <p>WishDrop (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) respects your privacy. This policy explains what data we collect, how we use it, and your rights regarding your personal information. WishDrop is operated at wishdrop.wagnerway.co.za.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-wd-heading mb-3">2. Data We Collect</h2>

            <h3 className="text-lg font-semibold text-wd-heading mt-4 mb-2">Data you provide:</h3>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>Registry creation:</strong> Registry name, occasion, event date, couple names, personal message, cover image URL, admin password (stored hashed, never in plain text).</li>
              <li><strong>Participant information:</strong> Name and optionally email address. Login codes are generated by the system and stored hashed.</li>
              <li><strong>Wishlist items:</strong> Item titles, product links, image URLs, prices, and priority levels.</li>
              <li><strong>Claims and notes:</strong> When claiming a gift, your name and optional personal message.</li>
              <li><strong>Cash fund pledges:</strong> Pledge amounts, personal messages, and contributor name.</li>
              <li><strong>RSVP data:</strong> Attendance status, headcount, and notes (Unlimited plan only).</li>
              <li><strong>Payment data:</strong> Processed by Stripe. We do not store credit card numbers. We store only Stripe customer and subscription IDs.</li>
            </ul>

            <h3 className="text-lg font-semibold text-wd-heading mt-4 mb-2">Data collected automatically:</h3>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>Analytics events:</strong> Page views and activity events (item claimed, guest joined) for registries on the Unlimited plan. These are aggregate counts, not personally identifiable.</li>
              <li><strong>Session data:</strong> We use HTTP-only cookies containing your participant ID, name, and registry ID. No third-party tracking cookies are used.</li>
              <li><strong>Rate limiting:</strong> IP addresses are temporarily stored in server memory for rate-limiting authentication requests. These are not persisted to disk or database.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-wd-heading mb-3">3. How We Use Your Data</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>To provide the gift registry service (displaying items, managing claims, tracking contributions).</li>
              <li>To authenticate you and protect your registry with secure sessions.</li>
              <li>To send transactional emails (magic link login, item claimed notifications) when you have provided an email address.</li>
              <li>To process payments through Stripe for the Unlimited plan.</li>
              <li>To provide analytics to registry owners on the Unlimited plan.</li>
            </ul>
            <p className="mt-2">We do <strong>not</strong> sell, rent, or share your personal data with third parties for marketing purposes.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-wd-heading mb-3">4. Data Sharing</h2>
            <p>Your data is shared only in these limited contexts:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li><strong>Within a registry:</strong> Participants can see each other&apos;s names and wishlist items. Claim information (who claimed what) is visible to other participants but hidden from the registry owner by default. The owner can enable &ldquo;reveal mode&rdquo; to see claimer names after the event.</li>
              <li><strong>Public registry page:</strong> If a registry has a public page (/r/slug), item titles, prices, categories, and claimed status are publicly visible. Claimer names are not shown on the public page.</li>
              <li><strong>Stripe:</strong> Payment information is sent directly to Stripe for processing. See <a href="https://stripe.com/privacy" className="text-wd-gold hover:underline" target="_blank" rel="noopener noreferrer">Stripe&apos;s Privacy Policy</a>.</li>
              <li><strong>Email provider:</strong> If email notifications are configured, your email address is sent to our SMTP provider for delivery.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-wd-heading mb-3">5. Data Security</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Admin passwords are hashed with bcrypt (12 rounds).</li>
              <li>Login codes are hashed with HMAC-SHA256 before storage.</li>
              <li>Magic link tokens are single-use and expire after 15 minutes.</li>
              <li>Sessions use HMAC-SHA256 signed HTTP-only cookies with timing-safe comparison.</li>
              <li>All authentication endpoints are rate-limited to prevent brute-force attacks.</li>
              <li>The application enforces HTTPS in production with secure cookie flags.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-wd-heading mb-3">6. Data Retention</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>Active registries:</strong> Stored for as long as the registry is active.</li>
              <li><strong>Inactive registries:</strong> May be deleted after 12 months of inactivity.</li>
              <li><strong>Magic link tokens:</strong> Expired tokens are not automatically purged but become unusable after 15 minutes.</li>
              <li><strong>Rate limit data:</strong> Stored in memory only; cleared on server restart.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-wd-heading mb-3">7. Your Rights</h2>
            <p>Depending on your jurisdiction (including under POPIA in South Africa, GDPR in the EU, and similar laws), you may have the right to:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li><strong>Access</strong> the personal data we hold about you.</li>
              <li><strong>Correct</strong> inaccurate or incomplete data.</li>
              <li><strong>Delete</strong> your data and registry (&ldquo;right to be forgotten&rdquo;).</li>
              <li><strong>Export</strong> your data (available via CSV export for Unlimited plan users).</li>
              <li><strong>Object</strong> to processing of your data.</li>
            </ul>
            <p className="mt-2">To exercise these rights, contact us. We will respond within 30 days.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-wd-heading mb-3">8. Cookies</h2>
            <p>WishDrop uses only <strong>essential cookies</strong> required for the Service to function:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li><code className="text-xs bg-white border border-wd-border px-1 py-0.5 rounded">wd_session</code> &mdash; Participant authentication session (7-day expiry).</li>
              <li><code className="text-xs bg-white border border-wd-border px-1 py-0.5 rounded">wd_admin_session</code> &mdash; Admin authentication session (7-day expiry).</li>
            </ul>
            <p className="mt-2">We do not use analytics cookies, advertising cookies, or any third-party tracking. No cookie consent banner is required because we only use strictly necessary cookies.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-wd-heading mb-3">9. Children&apos;s Privacy</h2>
            <p>WishDrop is not directed at children under 13. We do not knowingly collect personal data from children. If you believe a child has provided us with personal data, contact us and we will delete it.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-wd-heading mb-3">10. International Data</h2>
            <p>WishDrop may process data in countries other than your own. By using the Service, you consent to the transfer of your data to countries that may have different data protection standards. We take reasonable measures to protect your data regardless of where it is processed.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-wd-heading mb-3">11. Changes to This Policy</h2>
            <p>We may update this Privacy Policy from time to time. The &ldquo;Last updated&rdquo; date at the top reflects the most recent revision. Continued use of the Service after changes constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-wd-heading mb-3">12. Contact</h2>
            <p>For privacy-related questions or to exercise your data rights, contact us at the address provided on our website.</p>
          </section>

        </div>

        <div className="mt-12 pt-6 border-t border-wd-border text-center">
          <Link href="/terms" className="text-sm text-wd-gold hover:underline">Terms of Service</Link>
          <span className="text-wd-charcoal/30 mx-3">&bull;</span>
          <Link href="/" className="text-sm text-wd-gold hover:underline">Home</Link>
        </div>
      </div>
    </div>
  );
}
